### ISSUE TITLE
change oblogger icon

### ISSUE THREAD

**Issue by robotbrad** [loftTech/obsidian-oblogger#103]
obsidian has switched it's "tags" side-panel icon to the same one that we're using for oblogger in the current catalyst build.

here are my picks for new icon:
https://lucide.dev/icons/menu-square
https://lucide.dev/icons/app-window
https://lucide.dev/icons/panel-top
https://lucide.dev/icons/book-copy
https://lucide.dev/icons/square-stack
https://lucide.dev/icons/orbit

my favorite of the picks:
https://lucide.dev/icons/orbit
https://lucide.dev/icons/radar

i based my favorites on the likely hood that obsidian would ever use them for a feature of their own. :upside_down_face:

**Comment by msphair** [comment]
orbit is my favorite by far

**Comment by robotbrad** [comment]
fixed in #104
