### ISSUE TITLE
property otc groups

### ISSUE THREAD

**Issue by msphair** [loftTech/obsidian-oblogger#112]
the first level would show types as folders

the context menu on each type would have a "group by" sub menu which lists out all of the fields. When you select a field, each value in that field becomes a folder.

You can keep slicing it down more and more nested.

each folder should have a context menu option to "clear groupings" which collapses the nesting below it, removing the sub-folders

----

future work could have something like "re-assign" to a folder which would allow for mass-editing of metadata.

For example, right now, I have `type = health` and under that I have `what = note | action | treatment | meditation`. Meditation doesn't really fit into `health` anymore. I would like to group `health` by `what` and then right click `meditation` and change all of those to `type = meditation`.

**Comment by robotbrad** [comment]
we had a conversation about expanding this out into a bigger feature that allows adding "property" groups. we should repurpose this issue toward that goal. :+1:

**Comment by msphair** [comment]
@robotbrad should this be 0.9 or 1.0? I can't remember what we decided...

**Comment by robotbrad** [comment]
i think it should be the final big thing before releasing 0.9
