### ISSUE TITLE
Feature request of collapse button

### ISSUE THREAD

**Issue by azulika** [loftTech/obsidian-oblogger#127]
Splendid plugin, but a few feature requests:
- add collapse all button
- show the number of the notes with that tag in tag groups

Thank you!

**Comment by robotbrad** [comment]
hi @azulika! these are both great requests, we're going to use this ticket exclusively for the collapse all feature and i will create a new ticket for showing the number of notes within a tag group.

thanks for taking the time to use our plugin and also for giving us feedback!

**Comment by robotbrad** [comment]
expanded into #144
