### ISSUE TITLE
disambiguate matching tag groups

### ISSUE THREAD

**Issue by msphair** [loftTech/obsidian-oblogger#136]
![Image](https://github.com/loftTech/obsidian-oblogger/assets/1900880/0b8aa268-ab83-4832-b23d-3a316cb5bb15)

the top tag group is for `#gardening/tips`, the bottom group is for `#gardening/trees/tips`. When collapsed, they look identical. We could disambiguate them when we detect duplicates.

ie: if you add only `#gardening/tips` then it just shows `TIPS` like above. If you then add `#gardening/trees/tips` then it changes to `#gardening/tips` and `#.../trees/tips` (revealing the previous tag far enough to show a difference between them).

**Comment by robotbrad** [comment]
currently feel like this is a user issue, could reinvestigate if circumstances change
