### ISSUE TITLE
add ui for excluding folders

### ISSUE THREAD

**Issue by msphair** [loftTech/obsidian-oblogger#47]

**Comment by msphair** [comment]
assigning to @robotbrad to spec out the design for this

**Comment by robotbrad** [comment]
sent a document with specifications on freeform

**Comment by msphair** [comment]
![Image](https://github.com/loftTech/obsidian-oblogger/assets/1900880/bf2e738e-4aef-444f-b583-1a2e9e051c12)

**Comment by msphair** [comment]
~submenus might not be possible?~
~https://forum.obsidian.md/t/submenu-items-within-the-editor-context-menu/39699~

edit:

that's for the "editor" context menu, which might be a different beast

**Comment by msphair** [comment]
discord to the rescue

```ts
plugin.registerEvent(
      plugin.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item
            .setTitle("Plugin Name")
            .setIcon("bug")
            //@ts-ignore
            const submenu = item.setSubmenu() as Menu;
            submenu.addItem((subitem) => {
            subitem
              .setTitle("Submenu 1")
              .setIcon("arrow-right-circle")
              .onClick(async () => {
                 //function!
              });
          });        
        });
      })
    );
```

**Comment by msphair** [comment]
progress

<img width="364" alt="Screenshot 2023-08-24 at 22 40 06" src="https://github.com/loftTech/obsidian-oblogger/assets/1900880/e3581ee0-509c-4d91-ba83-765afe90290f">

**Comment by msphair** [comment]
trying to figure out how to handle the templates folder.

there are two places we could pull from:
- the templates core plugin
- the templater community plugin

both use different settings for the location of templates

**Comment by msphair** [comment]
here's how we would get to either of them

```
this.app.internalPlugins.plugins["templates"].instance.options.folder

this.app.plugins.plugins["templater-obsidian"].settings.templates_folder

```

**Comment by msphair** [comment]
we should reload when templates/templater settings change
