### ISSUE TITLE
entries is enabled, but not showing up

### ISSUE THREAD

**Issue by msphair** [loftTech/obsidian-oblogger#57]
![Image](https://github.com/loftTech/obsidian-oblogger/assets/1900880/64a6adc3-3d9f-40b6-9052-87298cf85fd9)

**Comment by msphair** [comment]
![Image](https://github.com/loftTech/obsidian-oblogger/assets/1900880/d94787a2-8dc5-4fac-adc5-67de0fff35f2)


looks like it was because of the settings name change from entries to dailies

**Comment by msphair** [comment]
had to delete all of the rx settings in `data.json` to get it to show up again

**Comment by robotbrad** [comment]
this was expected behavior, we'd talked about how it was a necessary evil in this case. eventually, by 1.0, we might want to consider having a less disruptive method when we need to change a setting that is currently stored in the json.

**Comment by msphair** [comment]
closing as it is tracked in #58
