### ISSUE TITLE
Breaks Workspaces core plugin

### ISSUE THREAD

**Issue by huachuman** [loftTech/obsidian-oblogger#94]
When I enable oblogger, switching workspaces results in the window going completely empty and I have to restart obsidian to get it to come back. Strangely, the workspace switch is not registered on restart either, resulting in it going back to the original workspace before the attempted switch.

Just to confirm, this is the core Workspaces plugin and NOT the Workspaces Plus community plugin.

The problem completely disappears when I disable oblogger and only appears when I enable it.

I am on the latest Obsidian version: v1.3.7, Installer version: v1.3.5

**Comment by robotbrad** [comment]
thanks so much for reporting this! are you building oblogger from git or from obsidian's community plugin catalogue?

**Comment by robotbrad** [comment]
this is pretty easy to reproduce.

1. enable plugin "oblogger"
2. enable core plugin "workspaces"
3. create a new workspace (i named mine "default).
4. attempt to load it with oblogger enabled, if reproduced it should just be a blank screen
5. disable plugin "oblogger"
6. attempt to load the workspace again and it should load everything normally

**Comment by robotbrad** [comment]
this is the error that posts when issue occurs.

![Screenshot from 2023-08-24 08-57-45](https://github.com/loftTech/obsidian-oblogger/assets/69363905/38edee7a-acd2-46b9-afcc-8e9bc499c744)

why am i not surprised to see the words `openFileContextMenu` 

@msphair this may be tied to #91 and #63. i think one solution is what we've already discussed as a possibility, re building the context menu from scratch. :sweat_smile:

**Comment by huachuman** [comment]
Updated the plugin, confirmed working now.
